---
development:
  cloud_name: dlrjff52b
  api_key: '417438166285767'
  api_secret: zEkUSbRqW92Zkbb_cuaFGmMrgg4
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dlrjff52b
  api_key: '417438166285767'
  api_secret: zEkUSbRqW92Zkbb_cuaFGmMrgg4
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dlrjff52b
  api_key: '417438166285767'
  api_secret: zEkUSbRqW92Zkbb_cuaFGmMrgg4
  enhance_image_tag: true
  static_image_support: false
